### ISSUE TITLE
Système d'étoile

### ISSUE THREAD

**Issue by Gabrielchebrou** [Corbichon/2017#19]
1 étoile : très facile à avoir
2 étoiles : pas facile à avoir
3 étoiles : très difficile à avoir

Etoile par rapport au score et pas par rapport à la complétiton/complétitudisation

Proposer de noter, après avoir obtenue 10 étoiles : ceux qui vont noté auront déjà saigné le jeu

**Comment by Corbichon** [comment]
https://github.com/DreaminginCodeZH/MaterialRatingBar

**Comment by Corbichon** [comment]
OK. Tout est configurable en live ici 
https://console.firebase.google.com/project/p2017-158610/config
